package ast

//============================================================================
// This file is generated by tool/ast-generate.go
// This file contains the interfaces used for AST nodes and tree walkers
// All edits should be made to the astInterfaceTemplate in ast-generate.go instead
//============================================================================

// Node is the common interface for all AST nodes
type Node interface {
	// Accept marshals the Visitor to the correct Visitor.visitMethod
	Accept(Visitor) interface{}
}

// Visitor is the interface used to implement visitor pattern for the AST
// Interpreter nodes with their visit methods are supposed to return nil as
// statements should resolve to a value
type Visitor interface {
	// visit Stmt node functions
	VisitExprStmt(*ExprStmt) interface{}
	VisitNameDeclStmt(*NameDeclStmt) interface{}

	// visit Expr node functions
	VisitNameExpr(*NameExpr) interface{}
	VisitGrpExpr(*GrpExpr) interface{}
	VisitBinExpr(*BinExpr) interface{}
	VisitUnExpr(*UnExpr) interface{}
	VisitBasicLit(*BasicLit) interface{}
}
