package ast

//============================================================================
// This file is generated by tool/ast-generate.go
// This file contains the interfaces used for AST nodes and tree walkers
// All edits should be made to the astInterfaceTemplate in ast-generate.go instead
//============================================================================

// Node is the common interface for all AST nodes
type Node interface {
	accept(Visitor) interface{}
}

// Visitor is the interface used to implement visitor pattern for the AST
type Visitor interface {
	// visit Expr node functions
	visitGrpExpr(*GrpExpr) interface{}
	visitBinExpr(*BinExpr) interface{}
	visitUnExpr(*UnExpr) interface{}
	visitBasicLit(*BasicLit) interface{}
}
